# Vision Model Training Configuration for TinierInceptionV1
dataset: "cifar100"
model_name: "TinierInceptionV1"
model_path: null
wandb: true
seed: 42
save_dir: "src/vision_modeling/models"
name_addon: "_tinier_aug"

# Training hyperparameters
batch_size: 64
num_workers: 4
prefetch_factor: 4
lr: 1e-3
epochs: 200
dropout: 0.3
weight_decay: 1e-4
label_smoothing: 0.1

# Transforms configuration
transforms:
  train:
    random_horizontal_flip: 0.5
    random_crop:
      size: 32
      padding: 4
    random_rotation: 15
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    normalize: true
  test:
    normalize: true
